#!/usr/bin/bash
#
# this file permits notify-send command to be used with sudo (root)
#
# move the notify-send-as-root file to /usr/bin/ and set permissions to allow execution 
#
# call notify-send-as-root in the same way that notify-send is used
#
# Assuming you have libnotify installed, then directions of how to use this command 
# can be found with this terminal command: man notify-send

PATH=/usr/bin:/bin 
{
	XUSERS=($(who|grep -E '\(:[0-9](\.[0-9])*\)' |awk '{print $1$NF}'|sort -u))
	for XUSER in ${XUSERS[@]} ; do
	    NAME=(${XUSER/(/ })
	    DISPLAY=${NAME[1]/)/}
	    DBUS_ADDRESS=unix:path=/run/user/$(id -u ${NAME[0]})/bus
	    sudo -u ${NAME[0]} DISPLAY=${DISPLAY} \
	                       DBUS_SESSION_BUS_ADDRESS=${DBUS_ADDRESS} \
	                       PATH=${PATH} \
	                       notify-send "$@"
	done
}

# source:
# https://gist.github.com/TopperBG/41449f4ed68cf692774eaabe69216e1f#file-notify-send-all
